import { StyleSheet } from 'react-native';

export const Style = StyleSheet.create({
  splashvew: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F2E9',
  },

  splashimg: {
    width: 180,
    height: 180,
  },

  mainvew: {
    flex: 1,
    backgroundColor: '#F5F2E9',
  },

  mainsubvew: {
    backgroundColor: '#E5E0D3',
    marginTop: 'auto',
    padding: 20,
    borderRadius: 20,
  },

  mainbtn: {
    backgroundColor: '#FE3D12',
    margin: 10,
    borderRadius: 50,
    padding: 10,
  },
  btnhover: {
    backgroundColor: '#1E1E1E',
    elevation: 5,
    shadowColor: '#FE3D12',
    transform: [{ scale: 1.05 }],
  },
  btntxt: {
    color: 'white',
    padding: 5,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  main2img: {
    flex: 1,
    justifyContent: 'center',
    width: 180,
    height: 180,
    margin: 10,
    alignSelf: 'center',
  },

  model1vew: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E5E0D3',
  },
  model2vew: {
    width: 300,
    height: 'auto',
    backgroundColor: 'white',
    padding: 20,
    margin: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  txtinpt: {
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 20,
  },

  gicon: {
    width: 22,
    height: 22,
    marginRight: 10,
    borderRadius: 20,
  },
  ficon: {
    width: 30,
    height: 30,
    marginRight: 10,
    borderRadius: 20,
  },

  chngedir: {
    flexDirection: 'row',
    padding: 10,
  },
  sidelogo: {
    position: 'absolute',
    width: 44.36,
    height: 40,
    alignSelf: 'flex-start',
    margin: 10,
    top: 0,
    left: 0,
    right: '100%',
    bottom: '100%',
  },
  inputvew: {
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 20,
    margin: 8,
  },
  placeholder: {
    position: 'absolute',
    left: 12,
    top: -9,
    backgroundColor: 'white',
    paddingHorizontal: 5,
    fontSize: 13,
    zIndex: 1,
  },
});

export const stylehome = StyleSheet.create({
  topview: {
    backgroundColor: '#E5E0D3',
    margin: 10,
    borderRadius: 55,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 'auto',
    height: 84,
    zIndex: 10,
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
  },
  buldbtn: {
    backgroundColor: '#FE3D12',
    margin: 10,
    padding: 10,
    borderRadius: 55,
    width: 150,
  },
  btnhover: {
    backgroundColor: '#1E1E1E',
    elevation: 5,
    shadowColor: '#FE3D12',
    transform: [{ scale: 1.05 }],
  },
  btntxt: {
    color: 'white',
    padding: 5,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  toplogo: {
    width: 154.68,
    height: 40,
    alignSelf: 'flex-start',
    margin: 20,
    padding: 10,
  },

  menulogo: {
    width: 44,
    height: 44,
    alignItems: 'center',
    margin: 20,
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 50,
  },

  menuvew: {
    position: 'absolute',
    width: 348.6,
    height: 200,
    backgroundColor: '#E5E0D3',
    zIndex: 10,
    alignSelf: 'center',
    top: 90,
    left: 15,
    right: 15,
    borderRadius: 20,
  },

  menutxt: {
    marginTop: 20,
    marginLeft: 20,
    fontWeight: 'bold',
  },

  titletxt: {
    fontSize: 36,
    lineHeight: 44,
    fontWeight: '600',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 16,
    padding: 0,
    textAlign: 'center',
  },
  semititle: {
    textAlign: 'center',
    margin: 10,
  },
  revimg1: {
    marginLeft: 10,
    width: 40,
    height: 40,
  },
  revimg: {
    marginLeft: -10,
    width: 40,
    height: 40,
  },
  star: {
    width: 80,
    height: 20,
    alignSelf: 'center',
  },
  bannerimg: {
    width: '100%',
    height: 430.29,
    alignSelf: 'center',
    marginTop: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  blackbord: {
    backgroundColor: 'black',
    height: 180,
    overflow: 'hidden',
  },
  brandlogs: {
    alignSelf: 'center',
    height: 80,
  },
  Logorow: {
    flexDirection: 'row',
  },
  cardvew: {
    backgroundColor: '#E5E0D3',
    margin: 20,
    borderRadius: 20,
  },
  cardlogo: {
    width: 322,
    height: 288.07,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 20,
  },
  overlay: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 0,
  },
  workvew: {
    backgroundColor: '#E5E0D3',
    alignSelf: 'center',
    marginTop: 40,
    padding: 20,
    borderRadius: 20,
  },
  workimg: {},
  dot: {
    position: 'absolute',
    right: -2,
    top: -2,

    backgroundColor: '#FE3D12',
    borderRadius: '100%',
    padding: 4,
  },
  bussinessimg: {
    width: 419.33,
    height: 209.67,
  },
  provew: {
    width: 210,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: 'black',
    borderRadius: 50,
    position: 'relative',
    overflow: 'hidden',
  },
  probtn: {
    position: 'absolute',
    backgroundColor: '#FE3D12',
    left: 3,
    width: 100,
    height: 40,
    borderRadius: 50,
  },
  option: {
    width: 105,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  protxt: {
    color: 'black',
    fontWeight: 'bold',
  },
  pricevew: {
    borderWidth: 2,
    borderColor: 'black',
    margin: 20,
    borderRadius: 20,
  },
  pricebtn: {
    backgroundColor: '#FE3D12',
    margin: 10,
    padding: 10,
    borderRadius: 55,
  },
  priceprovew: {
    margin: 20,
    borderRadius: 20,
  },
  Faqvew: {
    backgroundColor: '#E5E0D3',
    borderRadius: 20,
    padding: 20,
    margin: 10,
  },
  Faqvew2: {
    backgroundColor: '#E5E0D3',
    margin: 10,
    borderRadius: 20,
    padding: 20,
    borderColor: '#FE3D12',
    borderWidth: 2,
  },
  footer: {
    height: 1,
    backgroundColor: 'black',
    width: '100%',
    marginTop: 80,
  },
  footerimg: {
    width: 154.68,
    height: 40,
    margin: 10,
  },
});

export const cardstyle = StyleSheet.create({
  mainbtn: {
    backgroundColor: '#FE3D12',
    margin: 10,
    borderRadius: 50,
    padding: 10,
    width: 150,
  },
  btnhover: {
    backgroundColor: '#1E1E1E',
    elevation: 5,
    shadowColor: '#FE3D12',
    transform: [{ scale: 1.05 }],
  },
  btntxt: {
    color: 'white',
    padding: 5,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  sidebar: {
    position: 'absolute',
    backgroundColor: '#E5E0D3',
    height: '100%',
    paddingTop: 20,
    zIndex: 1,
    overflow: 'hidden',
  },
  sideimg: {
    width: 33.33,
    height: 60,
    margin: 10,
    alignSelf: 'center',
  },
  sideimg2: {
    width: 120,
    height: 60,
    margin: 10,
    alignSelf: 'center',
  },
  sidelogo: {
    width: 22,
    height: 21,
    margin: 8,
  },
  logoview: {
    flexDirection: 'row',
    margin: 8,
    alignItems: 'center',
    backgroundColor: 'white',
    overflow: 'scroll',
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
  },
  notselect: {
    flexDirection: 'row',
    margin: 8,
    alignItems: 'center',
    backgroundColor: '#E5E0D3',
    overflow: 'scroll',
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
  },
  otp: {
    borderBottomColor: 'black',
    borderBottomWidth: 1,
    height: 40,
    width: 30,
    fontSize: 15,
    textAlign: 'center',
  },
  otpview: {
    flexDirection: 'row',
    gap: 10,
    margin: 20,
    borderRadius: 20,
  },
  mainview: {
    marginLeft: 70,
  },
  title: {
    margin: 8,
    marginTop: 50,
    fontSize: 16,
    fontWeight: 'bold',
  },
  subview: {
    margin: 10,
    padding: 8,
    elevation: 5,
    alignSelf: 'center',
    borderRadius: 20,
    backgroundColor: '#E5E0D3',
    width: 300,
  },
  minitxt: {
    margin: 10,
    fontSize: 12,
  },
  filters: {
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    margin: 5,
  },

  filltertxt: {
    margin: 5,
    fontWeight: '500',
  },
  filterhovertxt: {
    margin: 5,
    fontWeight: '500',
    color: 'white',
  },
  filterhover: {
    backgroundColor: 'black',
    color: 'white',
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    margin: 5,
  },
  icon: {
    margin: 10,
    padding: 8,
    elevation: 5,
    alignSelf: 'center',
    borderRadius: 20,
    backgroundColor: '#E5E0D3',
    width: 'auto',
  },
  restpass: {
    borderBlockColor: 'gery',
    borderRadius: 20,
    padding: 'auto',
    margin: 10,
    alignSelf: 'flex-start',
    borderWidth: 1,
  },
  restpasstxt: {
    fontSize: 12,
    fontWeight: '500',
    margin: 5,
    padding: 5,
  },
  restinput: {
    borderColor: 'black',
    marginLeft: 10,
  },
  restinputtxt: {
    marginLeft: 5,
    marginTop: 10,
  },
  iconsize: {
    width: 22,
    height: 22,
    margin: 5,
  },
  plan: {
    margin: 10,
    alignSelf: 'center',
    borderRadius: 20,
    backgroundColor: 'white',
    width: '100%',
  },
});

export const Createcardstyle = StyleSheet.create({
  iphone: {
    width: '58%',
    height: '89%',
    alignSelf: 'center',
    marginTop: 20,
  },

  steps: {
    backgroundColor: '#E5E0D3',
    width: 30,
    alignItems: 'center',
    borderRadius: 50,
    margin: 20,
  },
  selectsteps: {
    backgroundColor: '#FE3D12',
    width: 30,
    alignItems: 'center',
    borderRadius: 50,
    margin: 20,
    color: 'white',
  },

  customcardview: {
    backgroundColor: '#E5E0D3',
    borderRadius: 20,
  },

  addimageview: {
    borderColor: 'black',
    borderStyle: 'dashed',
    padding: 20,
    margin: 15,
    borderWidth: 1,
    width: 150,
    height: 120,
    alignItems: 'center',
    borderRadius: 20,
    justifyContent: 'center',
    overflow: 'hidden',
  },

  customcardtxt: {
    alignSelf: 'flex-start',
    fontWeight: 'bold',
    fontSize: 18,
  },

  adddetailsview: {
    borderColor: 'black',
    borderStyle: 'solid',
    padding: 20,
    margin: 15,
    borderWidth: 1,
    width: 150,
    alignItems: 'center',
    borderRadius: 20,
  },
  gallaryimg: {
    width: 80,
    height: 80,
  },
  cameraicon: {
    width: 24,
    height: 24,
    alignSelf: 'center',
    marginTop: '50%',
  },
  companylogo: {
    width: 40,
    height: 30,
    position: 'absolute',
    zIndex: 10,
    left: 10,
    top: 10,
    borderRadius: 50,
  },
  profileimg: {
    width: '100%',
    height: '100%',
    borderRadius:20,
  },
  frame1: {
    position: 'absolute',
    width: '55%',
    height: '65%',
    top: 8,
    borderRadius: 20,
  },
  frame2: {
    backgroundColor: 'white',
    flex: 1,
    justifyContent: 'space-between',
    position: 'absolute',
    width: '55%',
    height: '34.6%',
    top: '54%',
    borderRadius: 20,
    borderTopColor: 'black',
    borderWidth: 0.5,

    zIndex:2 ,
    elevation: 10,
  },
  name: {
    fontSize: 20,
    fontWeight: 'bold',
    alignSelf: 'center',
    margin: 5,
    flexShrink: 1,
  },
  role: {
    fontSize: 10,
    alignSelf: 'center',
  },
  userinput: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    width: '75%',
    height: 20,
    backgroundColor: 'white',
  },
  callicon: {
    width: 10,
    height: 10,
    marginRight: 10,
    marginLeft: 10,
  },
  call: {
    fontSize: 8,
    flexShrink: 1,
  },
  savecontact: {
    backgroundColor: 'black',
    margin: 10,
    borderRadius: 20,
  },
  btntxt: {
    color: 'white',
    padding: 5,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  modelview: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modelsubview: {
    width: '85%',
    padding: 20,
    backgroundColor: '#F5F2E9',
    borderRadius: 15,
  },
  modeltxt: {
    marginLeft: 10,
    marginTop: 10,
    fontWeight: '600',
  },
  modelinput: {
    marginLeft: 10,
    borderColor: 'white',
    borderWidth: 1,
    borderRadius: 20,
    padding: 15,
  },
  modelviewbtn: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 20,
  },
  modelbtn: {
    backgroundColor: 'black',
    margin: 10,
    borderRadius: 20,
    padding: 10,
    width: 100,
    height: 50,
  },
  requiredmsg: {
    color: 'red',
    fontSize: 12,
    marginLeft: 10,
  },
});

export const bgimage = StyleSheet.create({
  Header: {
    backgroundColor: '#E5E0D3',
    padding: 10,
    borderRadius: 20,
  },
  custmbg: {
    margin: 10,
    borderColor: 'black',
    width: '100%',
    height: 200,
    borderRadius: 20,
    borderWidth: 1,
    alignSelf: 'center',
    padding:2
  },
  txt: {
    margin: 5,
    fontWeight: '600',
    color: 'grey',
    marginLeft: 20,
  },
  selecttxt: {
    margin: 5,
    fontWeight: '800',
    color: '#222',
    marginLeft: 20,
  },
  moveview: {
    position: 'absolute',
    bottom: 0,
    left: 30,
    height: 3,
    backgroundColor: '#FE3D12',
  },
  addimgview:{
    backgroundColor:"#222",
    padding:20,
    width:160,
    height:100,
    alignItems:"center",
    borderRadius:20,
    margin:10,


  }
});
